### ISSUE TITLE
"missing revert data in call exception"

### ISSUE THREAD

**Issue by peterbaker** [SansegoTek/DFKQuestRunner#19]
This may only be an issue on the Pokt network, but I believe I've seen it on main.

```
An error occured. Will attempt to retry in 180 seconds... Error: Error: missing revert data in call exception (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":144,\"error\":{\"message\":\"Relay attempts exhausted\",\"code\":-32050}}","error":{"code":-32050},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5100bd31b822371108a0f63dcfb6594b9919eaf4\",\"data\":\"0xdf52458a000000000000000000000000000000000000000000000000000000000000c823\"},\"latest\"],\"id\":144,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://harmony-0-rpc.gateway.pokt.network"}, data="0x", code=CALL_EXCEPTION, version=providers/5.5.1)
    at Logger.makeError (/Users/pete/Work/DFKQuestRunner/node_modules/@ethersproject/logger/lib/index.js:199:21)
    at Logger.throwError (/Users/pete/Work/DFKQuestRunner/node_modules/@ethersproject/logger/lib/index.js:208:20)
    at checkError (/Users/pete/Work/DFKQuestRunner/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:76:16)
    at JsonRpcProvider.<anonymous> (/Users/pete/Work/DFKQuestRunner/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:659:47)
    at step (/Users/pete/Work/DFKQuestRunner/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/pete/Work/DFKQuestRunner/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/pete/Work/DFKQuestRunner/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'missing revert data in call exception',
  code: 'CALL_EXCEPTION',
  error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":144,\"error\":{\"message\":\"Relay attempts exhausted\",\"code\":-32050}}", error={"code":-32050}, requestBody="{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5100bd31b822371108a0f63dcfb6594b9919eaf4\",\"data\":\"0xdf52458a000000000000000000000000000000000000000000000000000000000000c823\"},\"latest\"],\"id\":144,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://harmony-0-rpc.gateway.pokt.network", code=SERVER_ERROR, version=web/5.5.1)
```

**Comment by SansegoTek** [comment]
Thanks - I’m putting this type of error down to the ongoing issues with Harmony. I don’t think there’s anything I can do about it, and it should go away when Harmony starts behaving itself
